create table if not exists public.work_relationships (
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade,
 work_id text not null,
 work_title text not null,
 genre text,
 relationship text not null check (relationship in ('rewatch_always','rewatch','watched','dropped','unwatched','want_to_watch')),
 created_at timestamptz not null default now(),
 unique(user_id, work_id)
);
create index if not exists work_relationships_relationship_idx on public.work_relationships(relationship);
alter table public.work_relationships enable row level security;
create policy "demo read" on public.work_relationships for select using (true);
create policy "demo insert" on public.work_relationships for insert with check (true);
create policy "demo update" on public.work_relationships for update using (true) with check (true);
