-- TasteGraph v5: Supabase Schema
-- デモユーザーID（固定UUID）
-- DEMO_USER_ID = '00000000-0000-0000-0000-000000000000'

create table if not exists public.work_relationships (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  work_id text not null,
  work_title text not null,
  genre text,
  relationship text not null check (relationship in ('rewatch_always','rewatch','watched','dropped','unwatched','want_to_watch')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, work_id)
);

create index if not exists work_relationships_user_id_idx on public.work_relationships(user_id);
create index if not exists work_relationships_relationship_idx on public.work_relationships(relationship);

alter table public.work_relationships enable row level security;

-- デモモード用ポリシー（全ユーザーが全データにアクセス可能）
create policy "demo read" on public.work_relationships for select using (true);
create policy "demo insert" on public.work_relationships for insert with check (true);
create policy "demo update" on public.work_relationships for update using (true) with check (true);
create policy "demo delete" on public.work_relationships for delete using (true);

-- 本番モード用ポリシー（コメントアウト）
-- 認証実装時にこれに切り替える
-- create policy "user read" on public.work_relationships for select using (user_id = auth.uid());
-- create policy "user insert" on public.work_relationships for insert with check (user_id = auth.uid());
-- create policy "user update" on public.work_relationships for update using (user_id = auth.uid()) with check (user_id = auth.uid());
-- create policy "user delete" on public.work_relationships for delete using (user_id = auth.uid());
